bloodbank/urls.py
from django.urls import path
from .views import index, register, contactus, aboutus, campaign, what_is_blood, happy_giving, become_blood_donor, \
    gallery, donorinfo

app_name = 'bloodbank'

urlpatterns = [
    path('', index, name='index'),
    path('register', register, name='register'),
    path('aboutus', aboutus, name='aboutus'),
    path('campaign', campaign, name='campaign'),
    path('contactus', contactus, name='contactus'),
    path('what_is_blood', what_is_blood, name='what_is_blood'),
    path('happy_giving', happy_giving, name='happy_giving'),
    path('what_is_blood', what_is_blood, name='what_is_blood'),
    path('become_blood_donor', become_blood_donor, name='become_blood_donor'),
    path('gallery', gallery, name='gallery'),
    path('donorinfo', donorinfo, name='donorinfo'),

]

bloodbnk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('bloodbank.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloodbank/models.py
from django.db import models
from froala_editor.fields import FroalaField


# Create your models here.
class Donor(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=30)
    email = models.EmailField()
    DOB = models.DateField()
    bloodgroup = models.CharField(max_length=10)
    Date_of_last_donation = models.DateField()
    gender = models.CharField(max_length=6)
    state = models.CharField(max_length=10)
    weight = models.FloatField()
    not_suffer = models.CharField(max_length=100)
    eligibility = models.CharField(max_length=10)
    profile_pic = models.ImageField(upload_to='profile_pic')

    def __str__(self):
        return self.name


class Campaign(models.Model):
    campaign = models.ImageField()
    descriptions = FroalaField()


class ContactUs(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=50)
    message = models.TextField()

    class Meta:
        verbose_name_plural = "Contact Us"


class Gallery(models.Model):
    image = models.ImageField()
    pub_date = models.DateField()

    class Meta:
        verbose_name_plural = "Galleries"

bloodbank/forms.py
from django.forms import ModelForm
from .models import Donor, ContactUs


class DonorForm(ModelForm):
    class Meta:
        model = Donor
        fields = ['name', 'address', 'email', 'DOB', 'bloodgroup', 'Date_of_last_donation', 'gender', 'state', 'weight',
                  'not_suffer', 'eligibility', 'profile_pic']


class ContactForm(ModelForm):
    class Meta:
        model = ContactUs
        fields = ['email', 'subject', 'message']

bloodbank/views.py
from django.shortcuts import render, redirect
from .models import Donor, Campaign, ContactUs, Gallery
from .forms import DonorForm, ContactForm
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect


# from django.core.paginator import Paginator


# Create your views here.

def index(request):
    return render(request, 'index.html')


def aboutus(request):
    return render(request, 'aboutus.html')


def campaign(request):
    campaign = Campaign.objects.all()
    context = {
        'campaign': campaign
    }
    return render(request, 'campaign.html', context)


def what_is_blood(request):
    return render(request, 'what-_is_blood.html')


def become_blood_donor(request):
    return render(request, 'become_blood_donor.html')


def gallery(request):
    gallery = Gallery.objects.all().order_by('pub_date')
    context = {
        'gallery': gallery
    }
    return render(request, 'gallery.html', context)


def happy_giving(request):
    return render(request, 'happy_giving.html')


def contactus(request):
    contactus = ContactUs.objects.all()
    form = ContactForm()

    if request.method == 'POST':
        print(request.POST)
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Message send successfully.')

        else:
            print('error')
            messages.error(request, 'Messages are not sent.')
    context = {
        'contactus': contactus,

        'form': form
    }

    return render(request, 'contactus.html', context)


def register(request):
    donor = Donor.objects.all()
    form = DonorForm()

    if request.method == 'POST':
        print(request.POST)
        form = DonorForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            messages.success(request, 'Message send successfully.')
        else:
            print('error')
            messages.error(request, 'Messages are not sent.')

    context = {
        'donor': donor,
        'form': form
    }
    return render(request, 'register.html', context)


def donorinfo(request):
    if request.method == 'POST':
        blood_group = request.POST['bloodgroup']
        addresses = request.POST['address']
        if blood_group:
            if addresses:
                match = Donor.objects.filter(Q(bloodgroup__icontains=blood_group) &
                                             Q(address__icontains=addresses)
                                             )
                # paginator = Paginator(match, 3)
                # page = request.GET.get('page')
                # match = paginator.get_page(page)
                if match:
                    context = {
                        'match': match
                    }
                    return render(request, 'donorinfo.html', context)
                else:
                    messages.error(request, 'No result found!!')
        else:
            return HttpResponseRedirect('/donorinfo/')

    return render(request, 'donorinfo.html')

bloodbank/templates/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hamro Blood</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content=""/>
    <meta name="twitter:card" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'> -->

    <!-- Animate.css -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Superfish -->
    <link rel="stylesheet" href="{% static 'css/superfish.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">


    <!-- Modernizr JS -->
    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

</head>
<body>
<div id="fh5co-wrapper">
    <div id="fh5co-page">
        <header id="fh5co-header-section" class="sticky-banner">
            <div class="container">
                <div class="nav-header">
                    <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
                    <h1 id="fh5co-logo"><a href="base.html">Hamro Blood</a></h1>
                    <!-- START #fh5co-menu-wrap -->
                    <nav id="fh5co-menu-wrap" role="navigation">
                        <ul class="sf-menu" id="fh5co-primary-menu">
                            <li class="active">
                                <a href="{% url 'bloodbank:index' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'bloodbank:register' %}" class="fh5co-sub-ddown">Become a Donor</a>

                            </li>
                            <li>
                                <a href="{% url 'bloodbank:donorinfo' %}" class="fh5co-sub-ddown">Search Donor</a>
                            </li>
                            <li>
                                <a href="{% url 'bloodbank:campaign' %}" class="fh5co-sub-ddown">Campaigns</a>
                            </li>
                            <li>
                                <a href="{% url 'bloodbank:gallery' %}" class="fh5co-sub-ddown">Gallery</a>
                            </li>
                            <li>
                                <a href="{% url 'bloodbank:aboutus' %}" class="fh5co-sub-ddown">About Us</a>
                            </li>
                            <li>
                                <a href="{% url 'bloodbank:contactus' %}" class="fh5co-sub-ddown">Contact Us</a>
                            </li>

                    </nav>
                </div>
            </div>
        </header>


        <div class="section">
            <!-- container -->
            <div class="container">
                {% block content %} {% endblock %}
            </div>
            <!-- /container -->
        </div>
        <!-- fh5co-blog-section -->
        <footer>
            <div id="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 text-center">
                            <p class="fh5co-social-icons">
                                <a href="https://www.facebook.com/" class="fa fa-facebook"></a>
                                  <a href="https://www.twitter.com/" class="fa fa-twitter"></a>
                                   <a href="https://www.google.com/" class="fa fa-google"></a>
                                    <a href="https://www.youtube.com/" class="fa fa-youtube"></a>
                                     <a href="https://www.instagram.com/" class="fa fa-instagram"></a>

                            </p>
                            <p>Copyright 2019 Hamro Blood . All Rights Reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>


    </div>
    <!-- END fh5co-page -->

</div>
<!-- END fh5co-wrapper -->

<!-- jQuery -->


<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/sticky.js' %}"></script>

<!-- Stellar -->
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<!-- Superfish -->
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>

<!-- Main JS -->
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

bloodbank/templates/become_blood_donor.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <p>General Guidelines. To donate blood or platelets, you must be in good general health,
        weigh at least 110 pounds, and be at least 16 years old. Parental consent is required
        for blood donation by 16 year olds; 16 year olds are NOT eligible to donate
        platelets.</p><br>
    <img src="{% static 'images/blood1.jpg' %}" alt="blood donation" style="height: 400px; width: 500px">
    <img src="{% static 'images/blood2.jpg' %}" alt="blood donation" style="height: 400px; width: 500px">
    <h1><u>Power Red Donation</u></h1>
    <ul>
    <li>Donation frequency: Every 112 days, up to 3 times/year*; 2 times/year for male donors under age 18</li>
    <li>You must be in good health</li>
        <li><strong>Male donors</strong> must be at least 17 years old in most states, at least 5'1" tall and weigh at least 130 lbs</li>
        <li><strong>Female donors</strong> must be at least 19 years old, at least 5'5" tall and weigh at least 150 lbs</li>
    </ul>
{% endblock %}

bloodbank/templates/contactus.html
{% extends 'base.html' %}
{% block content %}
<form method="post" action="{% url 'bloodbank:contactus' %}">
 {% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">
  <strong>{{ message }}</strong>
</div>
        {% endfor %}
    {% endif %}
   <table align="center" width="50%">
  <thead><h1 align="center"><u>CONTACT US</u></h1></thead>
  <hr>
       {% csrf_token %}
    <tr><td>E-mail</td><td><input type="email" required placeholder="E-mail" name="email"></td></tr>
    <tr><td>Subject</td><td><input type="text" placeholder="subject" name="subject"></td></tr>
    <tr><td>Message</td><td><textarea placeholder="write message" name="message" ></textarea>
    <tr><td><button type="submit" value="submit" name="submit">send message</button></td></tr>
  </table>
</form>
    <br>
    <br>
    <table align="center">
     <tr><td><h2><u>You can also contact us through</u></h2><br></td></tr>
        <br><br>
    <br>
    </table>
    <table align="center" width="50%">
    <tr><td><h4>Email:</h4></td><td><h4>mepujan36@gmail.com</h4> </td></tr>
    <tr><td><h4>Mobile Number:</h4></td><td><h4>9862004829</h4> </td></tr>
    </table>
{% endblock %}

bloodbank/templates/donorinfo.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="{% url 'bloodbank:donorinfo' %}" >
        <div class="container" align="center">
            <center><h1>Search a Donor</h1>
                <p>Please provide the data to search the Donor..</p></center>
            <hr>
            <table align="center" width="87%">
                {% csrf_token %}

                <tr>
                    <td>Blood Type Required</td>
                    <td>
                        <select name="bloodgroup">
                            <option value="choose blood group">Choose Blood Group</option>
                            <option value="O+">O+</option>
                            <option value="O-">O-</option>
                            <option value="A+">A+</option>
                            <option value="B+">B+</option>
                            <option value="AB+">AB+</option>
                            <option value="AB-">AB-</option>
                            <option value="B-">B-</option>
                            <option value="A-">A-</option>
                        </select></td>
                    <td>
                    <td>&nbsp</td>
                    <td>Address</td>
                    <td>
                        <input type="text" placeholder="Enter address" name="address" required>
                    </td>
                    <td>&nbsp</td>
                    <td>

                        <button type="submit" value="submit" name="submit" style="height: 55px;width: 200px;">Search
                            Donors
                        </button>
                    </td>
                </tr>
            </table>
    </form>
    </div>
    <div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li style="color:red">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div style="color:blue">
        {% for info in match %}
            <table border="0px" width="300px">
                <tr>
                    <td>Name:</td>
                    <td>{{ info.name }}</td>
                </tr>
                <tr>
                    <td>Address:</td>
                    <td>{{ info.address }}</td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td>{{ info.email }}</td>
                </tr>
                <tr>
                    <td>DOB:</td>
                    <td>{{ info.DOB }}</td>
                </tr>
                <tr>
                    <td>Blood Group:</td>
                    <td>{{ info.bloodgroup }}</td>
                </tr>
                <tr>
                    <td>Date Of Last Donation:</td>
                    <td>{{ info.Date_of_last_donation }}</td>
                </tr>
                <tr>
                    <td>Gender:</td>
                    <td>{{ info.gender }}</td>
                </tr>
                <tr>
                    <td>State:</td>
                    <td>{{ info.state }}</td>
                </tr>
                <tr>
                    <td>Weight:</td>
                    <td>{{ info.weight }}</td>
                </tr>
                <tr>
                    <td>Eligibility:</td>
                    <td>{{ info.eligibility }}</td>
                </tr>
            <br>
            <br>
            </table>
            <table>
            <tr>
                    <td><img src="{{ info.profile_pic.url }}" style="height: 200px;width: 250px" alt=" "></td>
                </tr>
            </table>
        {% endfor %}
    </div>
{% endblock %}

bloodbank/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <img src="{% static 'images/ban.jpeg' %}" alt="" style="height: 500px;width: 1200px">
    <!-- end:header-top -->
    <div id="fh5co-features">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="feature-left">
                        <div class="feature-copy">
                            <h3>What is Blood?</h3>
                            <p>Blood is essential to life. Blood circulates through our body and delivers essential
                                substances like oxygen and nutrients to the body’s cells. It also transports metabolic
                                waste products away from those same cells. There is no substitute for blood. It cannot
                                be made or manufactured. Generous blood donors are the only source of blood for patients
                                in need of a blood transfusion.</p>
                            <p><a href="{% url 'bloodbank:what_is_blood' %}">Learn More</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">

                    <div class="feature-left">

                        <div class="feature-copy">
                            <h3>Become a Blood Donor</h3>
                            <p>General Guidelines. To donate blood or platelets, you must be in good general health,
                                weigh at least 110 pounds, and be at least 16 years old. Parental consent is required
                                for blood donation by 16 year olds; 16 year olds are NOT eligible to donate
                                platelets.</p>
                            <p><a href="{% url 'bloodbank:become_blood_donor' %}">Learn More</a></p>
                        </div>
                    </div>

                </div>

                <div class="col-md-4">
                    <div class="feature-left">
                        <div class="feature-copy">
                            <h3>Happy Giving</h3>
                            <p>Donating blood can help in treating patients suffering from cancer, bleeding disorders,
                                chronic anemia associated with cancer, sickle cell anemia, and other hereditary blood
                                abnormalities. It is important to know that human blood cannot be manufactured, people
                                are the only source of it and that is why it is important to donate blood and help those
                                who need it. It is also possible to store your own blood for your future needs. </p>
                            <p><a href="{% url 'bloodbank:happy_giving' %}">Learn More</a></p>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

    <div id="fh5co-feature-product" class="fh5co-section-gray">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center heading-section">
                    <h3>Giving is Virtue.</h3>
                    <p>“Bring a life back to power. Make blood donation your responsibility”</p>
                </div>
            </div>

            <h1>Why blood donation is important?</h1><br>
            <center>

                <iframe width="560" height="315" src="https://www.youtube.com/embed/obXjlquHlhE" frameborder="0"
                        allow="autoplay; encrypted-media" allowfullscreen></iframe>

            </center>


        </div>
    </div>


    <div id="fh5co-portfolio">
        <div class="container">

            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center heading-section animate-box">
                    <h3>Our Gallery</h3>
                    <p>Different Blood Donation Campaign held in different time..</p>
                </div>
            </div>
            <div class="row row-bottom-padded-md">
                <div class="col-md-12">
                    <ul id="fh5co-portfolio-list">
                            <li class="one-third animate-box" data-animate-effect="fadeIn">
                            <img src="{% static 'images/img1.jpg' %}" alt="" style="height: 270px;width: 360px">
                            </li>
                        <li class="one-third animate-box" data-animate-effect="fadeIn">
                            <img src="{% static 'images/img2.jpg' %}" alt="" style="height: 270px;width: 360px">
                        </li>
                        <li class="one-third animate-box" data-animate-effect="fadeIn">
                            <img src="{% static 'images/img3.jpg' %}" alt="" style="height: 270px;width: 360px">
                        </li>
                    </ul>


                    <div class="row">
                        <div class="col-md-4 col-md-offset-4 text-center animate-box">
                            <a href="{% url 'bloodbank:gallery' %}" class="btn btn-primary btn-lg">See Gallery</a>
                        </div>
                    </div>

                </div>
            </div>

{% endblock %}

bloodbank/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <!DOCTYPE html>
    <html>
    <head><title>Blood Donation Campaign</title>

        <style>
            a {
                color: dodgerblue;
            }

            select, #gender, ul, .container1 {
                width: 100%;
                padding: 16px 16px;
                border: none;
                border-radius: 4px;
                background-color: #f1f1f1;
            }

            .container1 {
                display: block;
                position: relative;
                padding-left: 35px;
                margin-bottom: 12px;
                cursor: pointer;
                font-size: 15px;
                -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
            }

            .container1 input {
                position: absolute;
                opacity: 0;
                cursor: pointer;
                height: 0;
                width: 0;
            }

            /* Create a custom checkbox */
            .checkmark {
                position: absolute;
                top: 0;
                left: 0;
                height: 25px;
                width: 25px;
                background-color: green;
            }

            /* On mouse-over, add a grey background color */
            .container1:hover input ~ .checkmark {
                background-color: #ccc;
            }

            /* When the checkbox is checked, add a blue background */
            .container1 input:checked ~ .checkmark {
                background-color: #2196F3;
            }

            /* Create the checkmark/indicator (hidden when not checked) */
            .checkmark:after {
                content: "";
                position: absolute;
                display: none;
            }

            .container1 input:checked ~ .checkmark:after {
                display: block;
            }

            /* Style the checkmark/indicator */
            .container1 .checkmark:after {
                left: 9px;
                top: 5px;
                width: 5px;
                height: 10px;
                border: solid white;
                border-width: 0 3px 3px 0;
                -webkit-transform: rotate(45deg);
                -ms-transform: rotate(45deg);
                transform: rotate(45deg);
            }

        </style>
    </head>
    <body>
    <form method="post" action="{% url 'bloodbank:register' %}" enctype="multipart/form-data">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success">
                    <strong>{{ message }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <div class="container">
            <h3 align="center">Register As a Donor</h3>
            <p>Please fill in this form to create an account.</p>
            <hr>
            {% csrf_token %}
            <label for="Name"><b>Full Name</b></label>
            <input type="text" placeholder="Enter name" name="name" required><br/>
            <label for="Address"><b>Current Address</b></label>
            <input type="text" placeholder="Enter address" name="address" required><br/>
            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="email" required>
            <label for="state"><b>State</b></label>
            <select name="state">
                <option value="select">Choose</option>
                <option value="state1">State 1</option>
                <option value="state2">State 2</option>
                <option value="state3">State 3</option>
                <option value="state4">State 4</option>
                <option value="state5">State 5</option>
                <option value="state6">State 6</option>
                <option value="state7">State 7</option>
            </select><br/><br/>
            <div id="gender">
                <label for="gender"><b>Gender</b></label>
                <input type="radio" name="gender" value="male" checked="male"/> Male
                <input type="radio" name="gender" value="female"/> Female
                <input type="radio" name="gender" value="other"/> Others
            </div>
            <br/>

            <label for="weight"><b>Weight</b></label>
            <input type="text" placeholder="weight" name="weight" required>

            <label for="bloodgroup"><b>Blood Group</b></label>
            <select name="bloodgroup">
                <option value="choose blood group">Choose your Blood Group</option>
                <option value="O+">O+</option>
                <option value="O-">O-</option>
                <option value="A+">A+</option>
                <option value="B+">B+</option>
                <option value="AB+">AB+</option>
                <option value="AB-">AB-</option>
                <option value="B-">B-</option>
                <option value="A-">A-</option>
            </select>
            <br/><br/>
            <label for="dateofbirth"><b>Date of Birth</b></label><br/><br/>
            <input type="date" name="DOB" required>
            <label for="mobilenumber"><b>Mobile Number</b></label>
            <input type="text" placeholder="Moblie Number" name="mobilenumber" required>
            <br/><br/>
            <label for="last_donate"><b>Date of Last Donation</b></label><br/>
            <input type="date" placeholder="Enter last donation date" name="Date_of_last_donation" required>
            {{ form.profile_pic }}
            <fieldset>
                <label for="eligibilitycheck"><b>Please check your eligibility to donate blood</b></label>

                <ul style="padding-left:30px;">
                    <li>My hemoglobin is not less than 12.5 grams</li>
                    <br/>
                    <li>I am free from acute respiratory diseases and skin diseases</li>
                    <br/>
                    <li>I do not carry any disease transmissible by blood transfusion</li>
                    <br/>
                    <li>I am not under medication for Malaria / Tuberculosis / Diabetes / Fits / Convulsions</li>
                    <br/>
                </ul>

                <h4>I havenot suffer from</h4>
                <label class="container1">Kidney Diseases
                    <input type="checkbox" name="not_suffer" checked>
                    <span class="checkmark"></span>
                </label>
                <label class="container1">Heart Diseases
                    <input type="checkbox" name="not_suffer">
                    <span class="checkmark"></span>
                </label>
                <label class="container1">AIDS
                    <input type="checkbox" name="not_suffer">
                    <span class="checkmark"></span>
                </label>
                <label class="container1">Cancer
                    <input type="checkbox" name="not_suffer">
                    <span class="checkmark"></span>
                </label>
                </label>
                <label class="container1">Hepatitis B, C
                    <input type="checkbox" name="not_suffer">
                    <span class="checkmark"></span>
                </label>
                <br/><br/>
                <div style="padding-left:10px;">
                    <font color="#FF0000">#</font>
                    <font>Please consult your physician to check for eligibility.
                    </font>
                </div>
                <br/><br/>
                <label>
                    <input type="checkbox" checked="checked" name="eligibility" style="margin-bottom:15px">
                    I have read the above eligibility criteria and confirm that I am eligible to donate blood.
                    <br/><br/>
            </fieldset>
            <br/>
            <p padding-right="10px">By creating an account you agree to our <a href="policy.htm"
                                                                               style="color:dodgerblue">Terms &
                Privacy</a>.</p>
            <button type="submit" value="submit" name="submit">Register</button>
        </div>
    </form>
    </fieldset>
    </body>
    </html>
{% endblock %}